# Generated by Django 3.1.2 on 2020-10-12 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='extensions',
        ),
        migrations.AddField(
            model_name='picture',
            name='extension',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pictures.extension'),
            preserve_default=False,
        ),
    ]
