# Generated by Django 3.1.2 on 2020-10-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20201012_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='url',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
