# Generated by Django 3.1.2 on 2020-10-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='JPG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('full_title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PNG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('full_title', models.CharField(max_length=64)),
            ],
        ),
    ]
