# Generated by Django 3.1.2 on 2020-12-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_auto_20201205_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='jpg',
            name='full_title',
            field=models.CharField(default='alma', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='png',
            name='full_title',
            field=models.CharField(default='as', max_length=64),
            preserve_default=False,
        ),
    ]
