# Generated by Django 3.1.2 on 2020-12-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0006_auto_20201205_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='GIF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('full_title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
    ]
